plugins:
  - rubocop-rspec

AllCops:
  Exclude:
    - "gemfiles/*"
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 100

Lint/RedundantRequireStatement:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/ClassLength:
  Max: 170

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Exclude:
    - "spec/hooks/checkin_mutex_spec.rb"
    - "spec/hooks/concurrency_spec.rb"
    - "spec/hooks/integration_spec.rb"
    - "spec/hooks/multi_database_spec.rb"
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

RSpec/InstanceVariable:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
