plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Max: 100

Lint/RedundantRequireStatement:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 3

RSpec/SpecFilePathFormat:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
